import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import type { InferGetStaticPropsType, GetStaticProps } from 'next'
import Hero from "@/components/Hero/Hero";

const inter = Inter({ subsets: ['latin'] })
type Page = {
  id: string,
  url: string,
}

export const getStaticProps: GetStaticProps<{
  page: Page
}> = async () => {
  const res = await fetch('https://adchitects-cms.herokuapp.com/page/MPz3uDxgKR', {
    headers: new Headers({
      "Authorization": `Basic ${btoa('adchitects:jsrulezzz')}`
    }),
  })
  console.log('paging', res)
  const page = await res.json()

  return { props: { page } }
}
export default function Home(props) {
const {page} = props
  console.log(page)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Hero />
        <Image
            src="/vercel.svg"
            alt="Vercel Logo"
            className={styles.vercelLogo}
            width={100}
            height={24}
            priority
        />


      </main>
    </>
  )

}
